version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: Awesome-xteve_server_1
      APP_PORT: 34400

  server:
    image: dnsforge/xteve:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./temp:/tmp