version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: awesome-xteve_server_1
      APP_PORT: 34400
    
  server:
    image: dnsforge/xteve:latest
    user: "1000:1000"
    init: true